---

- name: Create install directories
  file:
    path: "{{ vsphere_cpi_tmp_dir }}"
    state: directory
    mode: 0755

- name: Clone CPI git repo
  ansible.builtin.git:
    repo: "{{ vsphere_cpi_chart_repo }}"
    dest: "{{ vsphere_cpi_git_dir }}"

- name: Install CPI helm chart
  notify: Taint nodes
  kubernetes.core.helm:
    chart_ref: "{{ vsphere_cpi_git_dir }}/charts/vsphere-cpi"
    chart_version: "{{ vsphere_cpi_chart_version | default(omit) }}"
    release_name: "{{ vsphere_cpi_release_name }}"
    release_namespace: "{{ vsphere_cpi_namespace }}"
    release_state: "{{ vsphere_cpi_state }}"
    release_values:
      daemonset:
        nodeSelector: "{{ vsphere_cpi_ds_nodeselector }}"
        tag: "{{ vsphere_cpi_version }}"
      serviceAccount:
        name: "{{ vsphere_cpi_serviceaccount_name }}"
      config:
        enabled: true
        vcenter: "{{ vsphere_cpi_vcenter }}"
        datacenter: "{{ vsphere_cpi_datacenter }}"

        secret:
          create: false
          name: vsphere-creds  # reuse openshift secret

- name: Patch MachineSets to add taints to new Nodes
  loop: "{{ lookup('k8s', api_version='machine.openshift.io/v1beta1', kind='MachineSet', namespace='openshift-machine-api', wantlist=true) }}"
  loop_control:
    label: "{{ item.metadata.name }}"
  kubernetes.core.k8s:
    api_version: "{{ item.apiVersion }}"
    kind: "{{ item.kind }}"
    namespace: "{{ item.metadata.namespace }}"
    name: "{{ item.metadata.name }}"
    resource_definition:
      spec:
        template:
          spec:
            taints:
              - effect: NoSchedule
                key: node.cloudprovider.kubernetes.io/uninitialized
                value: "true"
