---

- name: Create vSphere CSI namespace
  kubernetes.core.k8s:
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ vsphere_csi_namespace }}"
    state: present

- name: Create vSphere CSI secret
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Secret
    namespace: "{{ vsphere_csi_namespace }}"
    name: "{{ vsphere_csi_secret_name }}"
    definition:
      data:
        csi-vsphere.conf: "{{ lookup('template', 'csi-vsphere.conf.j2') | b64encode }}"  # noqa var-spacing

- name: Download vSphere CSI Kubernetes manifests
  get_url:
    url: "{{ vsphere_csi_manifest_url }}"
    dest: "{{ vsphere_csi_tmp_location }}/vsphere-csi-driver.yaml"
    mode: '0660'

- name: Create SCC for CSI ServiceAccounts
  when: vsphere_csi_scc_assign | bool
  loop: "{{ vsphere_csi_scc | dict2items }}"
  kubernetes.core.k8s:
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: system:openshift:scc:{{ item.value.scc }}
    resource_definition:
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:openshift:scc:{{ item.value.scc }}
      subjects:
        - kind: ServiceAccount
          name: "{{ item.value.serviceaccount }}"
          namespace: "{{ vsphere_csi_namespace }}"

- name: Apply vSphere CSI Kubernetes manifests
  when: not ansible_check_mode
  kubernetes.core.k8s:
    state: present
    src: "{{ vsphere_csi_tmp_location }}/vsphere-csi-driver.yaml"
